ID=$1
OUTDIR=$2
INDIR=$3
WARCS=${@:4}

# This script is started by the commands generated by generate_tasks.sh.
# It runs warc2text once providing a batch of WARCs from $WARCS as an argument. Before running warc2text it changes
# the current directory to $INDIR. To fit many WARCs into the limitation of the command line length, pass the lowest
# common parent directory of all WARCs as INDIR and use shorter relative paths to WARCs.
# ${OUTDIR}/${ID} will contain the outputs and ${OUTDIR}_logs/${ID} the logs (stdout, stderr of warc2text).
FILTERDIR=$(realpath $(dirname $0))
LOGDIR=${OUTDIR%/}_logs

mkdir -p $LOGDIR $OUTDIR || exit 1
cd $INDIR
warc2text --encoding-errors replace --pdfpass ${OUTDIR}/${ID}/pdf --robotspass ${OUTDIR}/${ID}/robotstxt -f html,metadata --jsonl --compress zstd --compress-level 9 --skip-text-extraction --classifier skip --url-filters ${FILTERDIR}/url-filter-list.optimised -o ${OUTDIR}/${ID} $WARCS 2>${LOGDIR}/${ID}.stderr >${LOGDIR}/${ID}.stdout
