from pathlib import Path
import pandas as pd
from fire import Fire


def load_stats(stats_dir):
    """
    Load data generated by text_stats.sh
    """
    stats_dir = Path(stats_dir)
    ddf = pd.read_csv(stats_dir/'doc_stats.csv', sep='\s+') 
    tdf = pd.read_csv(stats_dir/'text_stats.csv', sep='\s+')

    for df in [ddf, tdf]:
        p = df.path.str.split('/')
        df['lang'] = p.str[-2]
        df['path'] = p.str.join('/')

    df = tdf.merge(ddf, on=['path','lang'], how='left', validate="1:1")
    df = df.drop(columns=['path'])
    return df

def reduce_stats(stats_dir):
    """
    Merges and reduces data generated by text_stats.sh into a single table language -> language stats.
    Saves this table to the input directory under the name stats.tsv.
    """
    df = load_stats(stats_dir)
    ldf = df.groupby("lang").agg('sum').reset_index()
    out_path = Path(stats_dir)/"stats.tsv"
    ldf.to_csv(out_path, sep='\t', index=False)
    print("Saved stats to ", out_path)


Fire(reduce_stats)
